{% set name = "sherpa" %}
{% set version = "2.2.16" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://gitlab.com/sherpa-team/sherpa/-/archive/v{{ version }}/sherpa-v{{ version }}.tar.gz
  sha256: b2680da5682c78623635ae88a5ff5af346cf74c1be95ee9177e8f9080d418e76
  patches:
    # Avoid issue with compiling .pyc files during packaging step post build
    - 0001-convert-print-statements-using-2to3.patch
    # Avoid issue with null characters in the prefix replacement
    - 0002-remove-null-characters-for-prefix-replacement.patch

build:
  # FIXME: Get macOS builds working
  skip: true  # [not linux]
  number: 3

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - {{ compiler('fortran') }}
    - gnuconfig  # [unix]
    - autoconf
    - libtool
    - make
    - automake
    - which
    - sed  # needed only to patch LDFLAGS
    - diffutils
    - texinfo  # can't skip build of manual
  host:
    - sqlite
    - lhapdf
    - hepmc2
  # note https://conda-forge.org/docs/maintainer/knowledge_base/#compilers
  # so don't add compilers to run or test requirements
  run:
    - lhapdf
    - hepmc2

test:
  requires:
    - lhapdf
    - hepmc2
  source_files:
    - Examples
  commands:
    - test -f $PREFIX/bin/Sherpa
    - test -f $PREFIX/bin/sconsloops  # FIXME: Broken (from MadLoop addon)
    - test -f $PREFIX/bin/get_bibtex
    - test -f $PREFIX/bin/Sherpa-config
    - test -f $PREFIX/bin/init_nlo.sh
    - test -f $PREFIX/bin/plot_graphs.sh
    - test -f $PREFIX/bin/make2scons  # FIXME: Has conda-forge build paths baked in
    - test -f $PREFIX/bin/plot_stats.sh

    - test -f $PREFIX/lib/SHERPA-MC/libPhasicProcess.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libMCatNLOCalculators.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libDireTools.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libPhasicMain.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libAhadicMain.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libToolsPhys.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libCT12Sherpa.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libDireLorentz.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libExtraXS.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libZfunctions.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libLundTools.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libRemnant.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libCSShowers.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libMCatNLOMain.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libSherpaPerturbativePhysics.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libDireGauge.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libShrimpsTools.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libMEToolsColors.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libSherpaSoftPhysics.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libCT10Sherpa.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libSherpaTools.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libGRVSherpa.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libAhadicDecays.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libMEToolsExplicit.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libHadronsMain.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libModelUFO.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libExtraXSCluster.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libMEToolsLoops.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libBeam.so.0 -  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libAhadicFormation.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libSherpaPythia.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libHadronsCurrents.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libPhasicDecays.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libMRST99Sherpa.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libAhadicTools.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libComix.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libExtraXS1_2.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libShrimpsBeamRemnants.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libMEToolsCurrents.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libPDFESherpa.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libMEToolsMain.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libModelMain.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libAmisicModel.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libAmegicCluster.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libLHAPDFSherpa.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libShrimpsMain.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libMEToolsSpinCorrelations.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libAmplitude.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libDireMain.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libPhasicEnhance.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libSherpaHEFT.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libShrimpsXsecs.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libSherpaMain.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libToolsOrg.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libMRST01LOSherpa.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libPDF.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libHadronsMEs.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libComixAmplitude.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libNNPDFSherpa.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libAmisic.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libSherpaHepMCOutput.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libMEToolsVertices.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libCSCalculators.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libExtraXS2_2.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libSherpaFusing.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libMCatNLOShowers.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libPhotonsMain.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libPhotonsTools.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libMCatNLOTools.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libString.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libMRST04QEDSherpa.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libPhotonsPhaseSpace.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libSherpaTauPi.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libMEProcess.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libComixCluster.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libAmegic.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libSherpaSingleEvents.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libPhotonsMEs.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libAmisicTools.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libExtraXSNLO.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libPhasicScales.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libDireShower.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libExtraXS1_3.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libAmegicPSGen.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libComixPhasespace.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libToolsMath.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libCTEQ6Sherpa.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libCSTools.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libHadronsPSs.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libCSMain.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libSherpaInitialization.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libPhasicChannels.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libPhasicSelectors.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libSherpaSM.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libDipoleSubtraction.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libMSTW08Sherpa.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libSherpaHiggs.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libShrimpsEvents.so.0  # [linux]
    - test -f $PREFIX/lib/SHERPA-MC/libShrimpsEikonals.so.0  # [linux]

    - Sherpa-config
    - Sherpa-config --version
    - Sherpa-config --prefix
    - Sherpa-config --incdir
    - Sherpa-config --libs
    - Sherpa-config --datadir
    - Sherpa-config --ldflags
    - Sherpa-config --cppflags

    - Sherpa --help
    - cd Examples/CI/LO_Z
    - Sherpa  # [build_platform == target_platform]

about:
  home: https://gitlab.com/sherpa-team/sherpa
  summary: 'A Monte Carlo event generator for the Simulation of High-Energy Reactions of PArticles '
  description: |
    Sherpa is a Monte Carlo event generator for the Simulation of High-Energy
    Reactions of PArticles in lepton-lepton, lepton-photon, photon-photon,
    lepton-hadron and hadron-hadron collisions. Simulation programs - also
    dubbed event generators - like Sherpa are indispensable work horses for
    current particle physics phenomenology and are (at) the interface between
    theory and experiment.
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  doc_url: https://sherpa-team.gitlab.io/
  dev_url: https://gitlab.com/sherpa-team/sherpa

extra:
  recipe-maintainers:
    - chrisburr
    - kratsg
    - matthewfeickert
